migg

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -274,16 +274,20 @@ jobs:
             npm install
             npm audit fix --audit-level=critical --force
             echo "After audit"
-            npm run migrations > migration_output.txt
+            npm run migrations:revert
+            exit 1
+            # npm run migrations > migration_output.txt
       - run:
           name: Send migration results to memstash
           command: |
             cd backend
             cat migration_output.txt
-            if grep "has been executed successfully" migrations_results.txt
+            if grep "has been executed successfully" migration_output.txt
             then
+              echo "Success"
               curl -H "Content-Type: text/plain" -H "token: 9db2fb2e-2626-4bce-aeae-c4ea05a9f1e8" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
             else
+              echo "Failure"
               curl -H "Content-Type: text/plain" -H "token: 9db2fb2e-2626-4bce-aeae-c4ea05a9f1e8" --request PUT --data "2" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
             fi
      # Here's where you will add some code to rollback on failure
